### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kingpin24** [kekesh/CMSC131#2]
In aug30.tex, I believe
` System.out.println("Their sum is " + first + second);`
should be
` System.out.println("Their sum is " + (first + second));`

Additionally,
`What does Math.random() do? It returns a pseudorandom number on the interval [0, 1].`
I believe it should be [0,1) here (and in immediately surrounding areas)

**Comment by kekesh** [comment]
You're right. I will make the changes later this week.

**Comment by kekesh** [comment]
Resolved - https://github.com/kekesh/CMSC131/commit/eab784d9d464e691292fdfc10399f3aba1dd6417
